services:
  - type: web
    name: test-sphere-be
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: chmod +x start.sh && ./start.sh
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: test-sphere-db
          property: connectionString
    autoDeploy: true
